# QuantConnect LEAN Configuration for Quant Bot
trading:
  # Universe configuration
  universe:
    equities: SP100  # S&P-100 stocks
    crypto: [BTCUSD, ETHUSD]
  
  # Bar timeframes
  bars:
    equities: 30m
    crypto: 15m
  
  # Risk management
  risk:
    per_trade_risk_pct: 0.01  # 1% risk per trade
    max_leverage: 2.0
    single_name_max_pct: 0.10  # 10% max per position
    sector_max_pct: 0.30    # 30% max per sector
    kill_switch_dd: 0.20    # 20% drawdown kill switch
    
  # Model paths
  models:
    classifier_path: models/xgb_classifier.joblib
    meta_model_path: models/meta_filter.joblib
    rl_policy_path: policies/ppo_policy.zip
  
  # Strategy parameters
  strategies:
    scalper_sigma:
      enabled: true
    trend_breakout:
      enabled: true
    bull_mode:
      enabled: true
    market_neutral:
      enabled: false
    gamma_reversal:
      enabled: false
  
  # Learning configuration
  learning:
    cv:
      scheme: purged_kfold_embargo
      folds: 5
      embargo_frac: 0.02
    retrain_cadence: weekly
  
  # Execution settings
  execution:
    maker_ladder_offsets_atr: [0.10, 0.20, 0.30]
    min_ms_between_orders: 300
