# QuantConnect LEAN Configuration for Quant Bot
trading:
  universe:
    equities: SP100
    crypto: [BTCUSD, ETHUSD]
  bars:
    equities: 30m
    crypto: 15m
  features:
    returns_periods: [1, 5, 20, 60]
    sma_periods: [20, 50, 200]
    ema_periods: [12, 26]
    macd_params: {fast: 12, slow: 26, signal: 9}
    atr_period: 14
    bollinger_period: 20
    vol_window: 20
  labels:
    horizon_bars: 5
    tp_atr_mult: 1.75
    sl_atr_mult: 1.0
  regime:
    enabled: true
    smooth_bars: 5
  capacity:
    adv_cap_pct: 0.05
  risk:
    per_trade_risk_pct: 0.01
    max_leverage: 2.0
    single_name_max_pct: 0.10
    sector_max_pct: 0.30
    crypto_max_gross_pct: 0.50
    vol_target_ann: 0.12
    kill_switch_dd: 0.20
    day_stop_dd: 0.06
    week_stop_dd: 0.10
    blackout:
      earnings: true
      fomc: true
  models:
    classifier_path: models/xgb_classifier.joblib
    meta_model_path: models/meta_filter.joblib
    rl_policy_path: policies/ppo_policy.zip
  strategies:
    scalper_sigma: {enabled: true}
    trend_breakout: {enabled: true}
    bull_mode: {enabled: true}
    market_neutral: {enabled: false}
    gamma_reversal: {enabled: false}
  learning:
    cv: {scheme: purged_kfold_embargo, folds: 5, embargo_frac: 0.02}
    retrain_cadence: weekly
    gates: {oos_sortino_min: 1.2, oos_profit_factor_min: 1.15, oos_max_dd_max: 0.06}
    meta_threshold: 0.58
  execution:
    maker_ladder_offsets_atr: [0.10, 0.20, 0.30]
    min_ms_between_orders: 300
    min_hold_secs: 60
    use_vector_env: true
  strategy_priority_by_regime:
    trend: [trend_breakout, bull_mode, scalper_sigma, market_neutral, gamma_reversal]
    chop: [scalper_sigma, market_neutral, gamma_reversal, trend_breakout, bull_mode]
    high-vol: [scalper_sigma, gamma_reversal, trend_breakout, market_neutral, bull_mode]
    low-vol: [trend_breakout, bull_mode, market_neutral, scalper_sigma, gamma_reversal]
  ui:
    discord: {enabled: true, guild_id: 0}
    admin_api: {enabled: true, host: "0.0.0.0", port: 8080, polling_interval_sec: 120}
