# QuantConnect LEAN Configuration for Quant Bot
trading:
  universe:
    equities: SP100
    crypto: [BTCUSD, ETHUSD]
  bars:
    equities: 30m
    crypto: 15m
  risk:
    per_trade_risk_pct: 0.01
    max_leverage: 2.0
    single_name_max_pct: 0.10
    sector_max_pct: 0.30
    asset_class_caps: { crypto_max_gross_pct: 0.50 }
    kill_switch_dd: 0.20
    vol_target_ann: 0.12
  models:
    classifier_path: models/xgb_classifier.joblib
    meta_model_path: models/meta_filter.joblib
    rl_policy_path: policies/ppo_policy.zip
  strategies:
    scalper_sigma: {enabled: true}
    trend_breakout: {enabled: true}
    bull_mode: {enabled: true}
    market_neutral: {enabled: false}
    gamma_reversal: {enabled: false}
  learning:
    cv: {scheme: purged_kfold_embargo, folds: 5, embargo_frac: 0.02}
    retrain_cadence: weekly
    gates: {oos_sortino_min: 1.2, oos_profit_factor_min: 1.15, oos_max_dd_max: 0.06}
  execution:
    maker_ladder_offsets_atr: [0.10, 0.20, 0.30]
    min_ms_between_orders: 300
    min_hold_secs: 60
